In [21]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [98]:
four=pd.read_excel('ahp_four.xlsx')
four=four.rename(columns={'Unnamed: 0':'dong_nm'})
four.set_index("dong_nm",inplace=True)

sum_rank=pd.read_excel('ahp_sum_rank.xlsx')
sum_rank=sum_rank.rename(columns={'Unnamed: 0':'dong_nm'})
sum_rank.set_index("dong_nm",inplace=True)

one_ratio=pd.read_excel('ahp_one_ratio.xlsx')
one_ratio=one_ratio.rename(columns={'Unnamed: 0':'dong_nm'})
one_ratio.set_index("dong_nm",inplace=True)

cc_value=pd.read_excel('ahp_cc_value.xlsx')
cc_value=cc_value.rename(columns={'Unnamed: 0':'dong_nm'})
cc_value.set_index("dong_nm",inplace=True)

sum_trans=pd.read_excel('ahp_sum_trans.xlsx')
sum_trans=sum_trans.rename(columns={'Unnamed: 0':'dong_nm'})
sum_trans.set_index("dong_nm",inplace=True)

#  four

In [23]:
#열별 합 구하기
four=pd.concat([four,(four.sum(axis='rows')).to_frame().T])
four.rename(index={0:'계'},inplace=True)
four

            환경      1인가구        상권      유동인구
환경    1.000000  2.300000  1.083333  1.133333
1인가구  0.434783  1.000000  0.833333  0.866667
상권    0.923077  1.200000  1.000000  1.083333
유동인구  0.882353  1.153846  0.923077  1.000000
계     3.240213  5.653846  3.839743  4.083333

In [24]:
#열별 합 1로 맞추고 행별 평균 구하기
four_norm=four.iloc[:5,:] / four.iloc[4]
four_norm

f_four=pd.concat([four_norm,pd.Series(four_norm.mean(axis='columns')).to_frame()],axis=1)
f_four.rename(columns={0:'상대비중'},inplace=True)
f_four

            환경      1인가구        상권      유동인구      상대비중
환경    0.308622  0.406803  0.282137  0.277551  0.318778
1인가구  0.134183  0.176871  0.217028  0.212245  0.185082
상권    0.284882  0.212245  0.260434  0.265306  0.255717
유동인구  0.272313  0.204082  0.240401  0.244898  0.240423
계     1.000000  1.000000  1.000000  1.000000  1.000000

# sum_rank

In [35]:
#열별 합 구하기
sum_rank=pd.concat([sum_rank,(sum_rank.sum(axis='rows')).to_frame().T])
sum_rank.rename(index={0:'계'},inplace=True)

In [36]:
#열별 합 1로 맞추고 행별 평균 구하기
sum_rank_norm=sum_rank.iloc[:66,:] / sum_rank.iloc[65]
sum_rank_norm

f_sum_rank=pd.concat([sum_rank_norm,pd.Series(sum_rank_norm.mean(axis='columns')).to_frame()],axis=1)
f_sum_rank.rename(columns={0:'환경_상대비중'},inplace=True)
f_sum_rank

,개포1동,개포2동,개포4동,논현1동,논현2동,대치1동,대치2동,대치4동,도곡1동,도곡2동,...,위례동,잠실2동,잠실3동,잠실4동,잠실6동,잠실7동,잠실본동,장지동,풍납1동,환경_상대비중
개포1동,0.008722,0.017013,0.015873,0.016382,0.013393,0.017013,0.005203,0.017013,0.015873,0.016382,...,0.012827,0.009463,0.004952,0.013297,0.012827,0.009881,0.007837,0.004952,0.010549,0.010836
개포2동,0.002907,0.005671,0.012698,0.012287,0.008929,0.005671,0.003469,0.005671,0.012698,0.012287,...,0.003207,0.007886,0.003714,0.011398,0.003207,0.007905,0.006270,0.003714,0.009042,0.005878
개포4동,0.001744,0.001418,0.003175,0.001365,0.001488,0.001418,0.002081,0.001418,0.003175,0.001365,...,0.001603,0.005914,0.002476,0.008865,0.001603,0.004941,0.004478,0.002476,0.007033,0.002574
논현1동,0.002181,0.001890,0.009524,0.004096,0.002232,0.001890,0.002601,0.001890,0.009524,0.004096,...,0.002138,0.006759,0.002971,0.009973,0.002138,0.005647,0.005225,0.002971,0.007912,0.003813
논현2동,0.002907,0.002836,0.009524,0.008191,0.004464,0.002836,0.002601,0.002836,0.009524,0.008191,...,0.002138,0.006759,0.003714,0.009973,0.002138,0.006588,0.005225,0.003714,0.009042,0.004285
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
잠실7동,0.034889,0.028355,0.025397,0.028669,0.026786,0.028355,0.041623,0.028355,0.025397,0.028669,...,0.032068,0.023658,0.044565,0.026595,0.032068,0.039526,0.062696,0.044565,0.021098,0.038731
잠실본동,0.034889,0.028355,0.022222,0.024573,0.026786,0.028355,0.041623,0.028355,0.022222,0.024573,...,0.032068,0.023658,0.044565,0.019946,0.032068,0.019763,0.031348,0.044565,0.021098,0.033146
장지동,0.026167,0.022684,0.019048,0.020478,0.017857,0.022684,0.020812,0.022684,0.019048,0.020478,...,0.019241,0.011829,0.014855,0.015957,0.019241,0.013175,0.010449,0.014855,0.015823,0.018347
풍납1동,0.052333,0.039698,0.028571,0.032765,0.031250,0.039698,0.052029,0.039698,0.028571,0.032765,...,0.038482,0.094632,0.059421,0.039892,0.038482,0.118577,0.094044,0.059421,0.063293,0.054307
계,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

# one_ratio

In [37]:
#열별 합 구하기
one_ratio=pd.concat([one_ratio,(one_ratio.sum(axis='rows')).to_frame().T])
one_ratio.rename(index={0:'계'},inplace=True)

In [38]:
#열별 합 1로 맞추고 행별 평균 구하기
one_ratio_norm=one_ratio.iloc[:66,:] / one_ratio.iloc[65]
one_ratio_norm

f_one_ratio=pd.concat([one_ratio_norm,pd.Series(one_ratio_norm.mean(axis='columns')).to_frame()],axis=1)
f_one_ratio.rename(columns={0:'1인가구_상대비중'},inplace=True)
f_one_ratio

,개포1동,개포2동,개포4동,논현1동,논현2동,대치1동,대치2동,대치4동,도곡1동,도곡2동,...,위례동,잠실2동,잠실3동,잠실4동,잠실6동,잠실7동,잠실본동,장지동,풍납1동,1인가구_상대비중
개포1동,0.006452,0.009685,0.003819,0.008340,0.005338,0.011236,0.009756,0.006188,0.003359,0.009238,...,0.010480,0.012109,0.011605,0.012903,0.012685,0.012552,0.012422,0.012821,0.012346,0.007047
개포2동,0.003226,0.004843,0.002546,0.007297,0.005338,0.007491,0.002439,0.004950,0.003359,0.009238,...,0.002620,0.003027,0.007737,0.008602,0.008457,0.008368,0.008282,0.008547,0.008230,0.004554
개포4동,0.012903,0.014528,0.007638,0.009730,0.006673,0.014981,0.014634,0.006188,0.013438,0.013857,...,0.015721,0.012109,0.011605,0.012903,0.012685,0.012552,0.012422,0.012821,0.012346,0.008857
논현1동,0.045161,0.038741,0.045831,0.058378,0.106762,0.029963,0.039024,0.099010,0.047032,0.036952,...,0.036681,0.042381,0.030948,0.034409,0.033827,0.033473,0.033126,0.034188,0.032922,0.055987
논현2동,0.032258,0.024213,0.030554,0.014594,0.026690,0.022472,0.024390,0.049505,0.033595,0.027714,...,0.026201,0.030272,0.023211,0.025806,0.025370,0.025105,0.024845,0.025641,0.024691,0.030876
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
잠실7동,0.002151,0.002421,0.002546,0.007297,0.004448,0.007491,0.002439,0.004125,0.002240,0.002309,...,0.002620,0.002018,0.007737,0.002151,0.002114,0.004184,0.008282,0.002137,0.008230,0.003542
잠실본동,0.002151,0.002421,0.002546,0.007297,0.004448,0.007491,0.002439,0.004125,0.002240,0.002309,...,0.002620,0.002018,0.007737,0.002151,0.002114,0.002092,0.004141,0.002137,0.008230,0.003435
장지동,0.002151,0.002421,0.002546,0.007297,0.004448,0.007491,0.002439,0.004125,0.002240,0.002309,...,0.002620,0.002018,0.007737,0.002151,0.008457,0.008368,0.008282,0.004274,0.008230,0.003759
풍납1동,0.002151,0.002421,0.002546,0.007297,0.004448,0.007491,0.002439,0.004125,0.002240,0.002309,...,0.002620,0.002018,0.007737,0.002151,0.002114,0.002092,0.002070,0.002137,0.004115,0.003340
계,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

# cc_value

In [39]:
#열별 합 구하기
cc_value=pd.concat([cc_value,(cc_value.sum(axis='rows')).to_frame().T])
cc_value.rename(index={0:'계'},inplace=True)

In [40]:
#열별 합 1로 맞추고 행별 평균 구하기
cc_value_norm=cc_value.iloc[:66,:] / cc_value.iloc[65]
cc_value_norm

f_cc_value=pd.concat([cc_value_norm,pd.Series(cc_value_norm.mean(axis='columns')).to_frame()],axis=1)
f_cc_value.rename(columns={0:'상권_상대비중'},inplace=True)
f_cc_value

,개포1동,개포2동,개포4동,논현1동,논현2동,대치1동,대치2동,대치4동,도곡1동,도곡2동,...,위례동,잠실2동,잠실3동,잠실4동,잠실6동,잠실7동,잠실본동,장지동,풍납1동,상권_상대비중
개포1동,0.002188,0.002188,0.000767,0.002487,0.002487,0.002487,0.002487,0.002487,0.002487,0.000767,...,0.002487,0.000767,0.002188,0.002487,0.002487,0.002188,0.002487,0.000792,0.002188,0.002067
개포2동,0.002188,0.002188,0.000767,0.002487,0.002487,0.002487,0.002487,0.002487,0.002487,0.000767,...,0.002487,0.000767,0.002188,0.002487,0.002487,0.002188,0.002487,0.000792,0.002188,0.002067
개포4동,0.008753,0.008753,0.003067,0.003198,0.003198,0.003198,0.003198,0.003198,0.003198,0.003067,...,0.003198,0.003067,0.008753,0.003198,0.003198,0.008753,0.003198,0.001386,0.008753,0.003898
논현1동,0.019694,0.019694,0.021472,0.022386,0.022386,0.022386,0.022386,0.022386,0.022386,0.021472,...,0.022386,0.021472,0.019694,0.022386,0.022386,0.019694,0.022386,0.022176,0.019694,0.021879
논현2동,0.019694,0.019694,0.021472,0.022386,0.022386,0.022386,0.022386,0.022386,0.022386,0.021472,...,0.022386,0.021472,0.019694,0.022386,0.022386,0.019694,0.022386,0.022176,0.019694,0.021879
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
잠실7동,0.002188,0.002188,0.000767,0.002487,0.002487,0.002487,0.002487,0.002487,0.002487,0.000767,...,0.002487,0.000767,0.002188,0.002487,0.002487,0.002188,0.002487,0.000792,0.002188,0.002067
잠실본동,0.019694,0.019694,0.021472,0.022386,0.022386,0.022386,0.022386,0.022386,0.022386,0.021472,...,0.022386,0.021472,0.019694,0.022386,0.022386,0.019694,0.022386,0.022176,0.019694,0.021879
장지동,0.015317,0.015317,0.012270,0.005597,0.005597,0.005597,0.005597,0.005597,0.005597,0.012270,...,0.005597,0.012270,0.015317,0.005597,0.005597,0.015317,0.005597,0.005544,0.015317,0.007773
풍납1동,0.002188,0.002188,0.000767,0.002487,0.002487,0.002487,0.002487,0.002487,0.002487,0.000767,...,0.002487,0.000767,0.002188,0.002487,0.002487,0.002188,0.002487,0.000792,0.002188,0.002067
계,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

#  sum_trans

In [62]:
#열별 합 구하기
sum_trans=pd.concat([sum_trans,(sum_trans.sum(axis='rows')).to_frame().T])
sum_trans.rename(index={0:'계'},inplace=True)

In [64]:
#열별 합 1로 맞추고 행별 평균 구하기
sum_trans_norm=sum_trans.iloc[:66,:] / sum_trans.iloc[65]
sum_trans_norm

f_sum_trans=pd.concat([sum_trans_norm,pd.Series(sum_trans_norm.mean(axis='columns')).to_frame()],axis=1)
f_sum_trans.rename(columns={0:'유동인구_상대비중'},inplace=True)
f_sum_trans

,개포1동,개포2동,개포4동,논현1동,논현2동,대치1동,대치2동,대치4동,도곡1동,도곡2동,...,위례동,잠실2동,잠실3동,잠실4동,잠실6동,잠실7동,잠실본동,장지동,풍납1동,유동인구_상대비중
개포1동,0.005618,0.003049,0.003165,0.006061,0.005859,0.004329,0.007199,0.005181,0.003922,0.003571,...,0.010724,0.003436,0.004587,0.004132,0.003992,0.003503,0.010638,0.009442,0.004219,0.004957
개포2동,0.011236,0.006098,0.003165,0.006061,0.005859,0.004329,0.007199,0.005181,0.003922,0.003571,...,0.010724,0.005155,0.004587,0.004132,0.003992,0.005254,0.010638,0.009442,0.004219,0.005901
개포4동,0.011236,0.012195,0.006329,0.007273,0.005859,0.004329,0.007199,0.005181,0.003922,0.005357,...,0.010724,0.005155,0.004587,0.004132,0.003992,0.005254,0.010638,0.009442,0.004219,0.006255
논현1동,0.033708,0.036585,0.031646,0.036364,0.058594,0.043290,0.021598,0.051813,0.039216,0.053571,...,0.032172,0.051546,0.045872,0.041322,0.047904,0.052539,0.031915,0.018885,0.042194,0.041780
논현2동,0.028090,0.030488,0.031646,0.018182,0.029297,0.034632,0.014399,0.051813,0.031373,0.042857,...,0.026810,0.041237,0.036697,0.033058,0.047904,0.042032,0.026596,0.015108,0.033755,0.035135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
잠실7동,0.016854,0.012195,0.012658,0.007273,0.007324,0.017316,0.008639,0.006477,0.015686,0.005357,...,0.016086,0.020619,0.018349,0.016529,0.005988,0.010508,0.015957,0.010791,0.016878,0.012982
잠실본동,0.002809,0.003049,0.003165,0.006061,0.005859,0.004329,0.007199,0.005181,0.003922,0.003571,...,0.002681,0.003436,0.004587,0.004132,0.003992,0.003503,0.005319,0.009442,0.004219,0.004177
장지동,0.044944,0.048780,0.050633,0.145455,0.146484,0.060606,0.172786,0.129534,0.062745,0.075000,...,0.042895,0.072165,0.064220,0.057851,0.083832,0.073555,0.042553,0.075540,0.059072,0.072262
풍납1동,0.011236,0.012195,0.012658,0.007273,0.007324,0.004329,0.008639,0.006477,0.015686,0.005357,...,0.010724,0.005155,0.004587,0.016529,0.005988,0.005254,0.010638,0.010791,0.008439,0.009485
계,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

# 최적 상대적 중요도 도출

In [65]:
# 요인별 상대비중

sdbj=f_four[['상대비중']].iloc[:4,:]
sdbj

          상대비중
환경    0.318778
1인가구  0.185082
상권    0.255717
유동인구  0.240423

In [94]:
# 행정동별 상대비중

dsdbj=pd.concat([f_sum_rank[['환경_상대비중']],f_one_ratio[['1인가구_상대비중']],\
           f_cc_value[['상권_상대비중']],f_sum_trans[['유동인구_상대비중']]],axis=1)
dsdbj=dsdbj.iloc[:65,:]
dsdbj

       환경_상대비중  1인가구_상대비중   상권_상대비중  유동인구_상대비중
개포1동  0.010836   0.007047  0.002067   0.004957
개포2동  0.005878   0.004554  0.002067   0.005901
개포4동  0.002574   0.008857  0.003898   0.006255
논현1동  0.003813   0.055987  0.021879   0.041780
논현2동  0.004285   0.030876  0.021879   0.035135
...        ...        ...       ...        ...
잠실6동  0.007086   0.003650  0.021879   0.015057
잠실7동  0.038731   0.003542  0.002067   0.012982
잠실본동  0.033146   0.003435  0.021879   0.004177
장지동   0.018347   0.003759  0.007773   0.072262
풍납1동  0.054307   0.003340  0.002067   0.009485

[65 rows x 4 columns]

In [97]:
# 두 행렬 곱해서 최종점수 도출

ff=pd.DataFrame(np.dot(dsdbj,sdbj))
ff.index=['개포1동', '개포2동', '개포4동', '논현1동', '논현2동', '대치1동', '대치2동', '대치4동', '도곡1동',
       '도곡2동', '삼성1동', '삼성2동', '세곡동', '수서동', '신사동', '압구정동', '역삼1동', '역삼2동',
       '일원1동', '일원2동', '일원본동', '청담동', '가양1동', '가양2동', '가양3동', '공항동', '등촌1동',
       '등촌2동', '등촌3동', '발산1동', '방화1동', '방화2동', '방화3동', '염창동', '우장산동', '화곡1동',
       '화곡2동', '화곡3동', '화곡4동', '화곡8동', '화곡본동', '가락1동', '가락2동',
       '거여1동', '거여2동', '마천1동', '마천2동', '문정1동', '문정2동', '방이1동', '방이2동', '삼전동',
       '송파1동', '송파2동', '오금동', '오륜동', '위례동', '잠실2동', '잠실3동', '잠실4동',
       '잠실6동', '잠실7동', '잠실본동', '장지동', '풍납1동']
ff.rename(columns={0:'최종점수'},inplace=True)

fff=pd.concat([dsdbj,ff],axis=1)
fff=fff.sort_values(['최종점수'],ascending=False)
fff

       환경_상대비중  1인가구_상대비중   상권_상대비중  유동인구_상대비중      최종점수
역삼1동  0.015791   0.072607  0.021879   0.089339  0.045546
화곡1동  0.038731   0.022958  0.021879   0.044535  0.032898
방이2동  0.033146   0.041980  0.021879   0.026777  0.030369
잠실4동  0.064523   0.003858  0.021879   0.009257  0.029103
논현1동  0.003813   0.055987  0.021879   0.041780  0.027218
...        ...        ...       ...        ...       ...
염창동   0.003207   0.005811  0.007773   0.009681  0.006413
도곡2동  0.003813   0.004234  0.003898   0.013413  0.006221
일원2동  0.005878   0.009922  0.002067   0.007882  0.006133
개포4동  0.002574   0.008857  0.003898   0.006255  0.004960
개포2동  0.005878   0.004554  0.002067   0.005901  0.004664

[65 rows x 5 columns]

In [1]:
fff.to_excel('ahp_final')

NameError: name 'fff' is not defined